# Generated by Django 5.2.17 on 2026-10-01 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('yuque', 'Yuque'), ('wechat', 'Wechat')], max_length=16)),
                ('canonical_locator', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], max_length=8)),
                ('authorization_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('revoked', 'Revoked')], max_length=12)),
                ('authorization_note', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('withdrawn', 'Withdrawn')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_source',
                'permissions': [('read_internal', '读取内部资料'), ('maintain_source', '维护来源'), ('review_import', '复核导入'), ('manage_runtime', '管理运行配置')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='catalog.knowledgesource')),
                ('base_build_id', models.UUIDField(null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('input_text', models.TextField()),
                ('format', models.CharField(choices=[('txt', 'Txt'), ('markdown', 'Markdown')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('source_metadata', models.JSONField(default=dict)),
                ('domain_metadata', models.JSONField(default=dict)),
                ('document_schema', models.CharField(max_length=64)),
                ('schema_version', models.PositiveIntegerField()),
                ('index_profile', models.JSONField(default=dict)),
                ('index_profile_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('quality_report', models.JSONField(default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('current_step', models.CharField(default='submitted', max_length=32)),
                ('error_code', models.CharField(max_length=64, null=True)),
                ('error_detail', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_imports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_job',
            },
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='current_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_sources', to='catalog.importjob'),
        ),
        migrations.CreateModel(
            name='ContextUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('scope_fields', models.JSONField(default=dict)),
                ('locator', models.JSONField(default=dict)),
                ('field_sources', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('knowledge_types', models.JSONField(default=list)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='catalog.importjob')),
            ],
            options={
                'db_table': 'context_unit',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('index_profile', models.JSONField(default=dict)),
                ('index_profile_hash', models.CharField(max_length=64)),
                ('query_profile', models.JSONField(default=dict)),
                ('query_profile_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'retrieval_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='settings_singleton')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('knowledge_type', models.CharField(max_length=32)),
                ('evidence_role', models.CharField(max_length=32)),
                ('context_role', models.CharField(max_length=32)),
                ('body', models.TextField()),
                ('retrieval_text', models.TextField()),
                ('locator', models.JSONField(default=dict)),
                ('structured_fields', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.contextunit')),
            ],
            options={
                'db_table': 'evidence_unit',
                'ordering': ['ordinal'],
                'constraints': [models.UniqueConstraint(fields=('context', 'ordinal'), name='evidence_ordinal_unique'), models.CheckConstraint(condition=models.Q(('ordinal__gte', 1)), name='evidence_ordinal_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='contextunit',
            constraint=models.UniqueConstraint(fields=('build', 'ordinal'), name='context_ordinal_unique'),
        ),
        migrations.AddConstraint(
            model_name='contextunit',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gte', 1)), name='context_ordinal_positive'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(fields=('source_type', 'canonical_locator'), name='source_locator_unique'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['manual', 'yuque', 'wechat'])), name='source_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'internal'])), name='source_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(('authorization_status__in', ['confirmed', 'pending', 'revoked'])), name='source_auth_valid'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'disabled', 'withdrawn'])), name='source_status_valid'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['source', 'content_hash', 'index_profile_hash'], name='job_dedupe_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'created_at'], name='job_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'succeeded', 'failed'])), name='job_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'approved', 'rejected'])), name='job_review_valid'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('format__in', ['txt', 'markdown'])), name='job_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='job_schema_positive'),
        ),
    ]
