# Generated by Django 5.2.17 on 2026-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceunit',
            name='context_role',
            field=models.CharField(choices=[('main', 'Main'), ('prerequisite', 'Prerequisite'), ('warning', 'Warning'), ('result_branch', 'Result Branch'), ('support', 'Support')], max_length=32),
        ),
        migrations.AlterField(
            model_name='evidenceunit',
            name='evidence_role',
            field=models.CharField(choices=[('source_statement', 'Source Statement'), ('measured_fact', 'Measured Fact'), ('author_opinion', 'Author Opinion'), ('repair_observation', 'Repair Observation'), ('confirmed_result', 'Confirmed Result'), ('hypothesis', 'Hypothesis'), ('mixed', 'Mixed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='evidenceunit',
            name='knowledge_type',
            field=models.CharField(choices=[('concept', 'Concept'), ('product_spec', 'Product Spec'), ('purchase_recommendation', 'Purchase Recommendation'), ('repair_case', 'Repair Case'), ('procedure', 'Procedure'), ('faq', 'Faq')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='evidenceunit',
            constraint=models.CheckConstraint(condition=models.Q(('knowledge_type__in', ['concept', 'product_spec', 'purchase_recommendation', 'repair_case', 'procedure', 'faq'])), name='evidence_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='evidenceunit',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_role__in', ['source_statement', 'measured_fact', 'author_opinion', 'repair_observation', 'confirmed_result', 'hypothesis', 'mixed'])), name='evidence_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='evidenceunit',
            constraint=models.CheckConstraint(condition=models.Q(('context_role__in', ['main', 'prerequisite', 'warning', 'result_branch', 'support'])), name='evidence_context_role_valid'),
        ),
    ]
