# Generated by Django 5.2.17 on 2026-10-01 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


def require_empty_legacy_catalog(apps, schema_editor):
    # 本轮更换存储契约；拒绝静默删除旧库正文、候选或权限信息。
    if apps.get_model("catalog", "KnowledgeSource").objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            "旧版知识库仍有资料，精简迁移已中止。请保留旧库备份，使用新数据库，"
            "将所需资料整理为 ProcessedDocument 后导入；不要删除旧库规避检查。"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_evidenceunit_context_role_and_more'),
    ]

    operations = [
        migrations.RunPython(require_empty_legacy_catalog),
        migrations.RemoveField(
            model_name='KnowledgeSource',
            name='current_build',
        ),
        migrations.DeleteModel(
            name='EvidenceUnit',
        ),
        migrations.DeleteModel(
            name='ContextUnit',
        ),
        migrations.DeleteModel(
            name='ImportJob',
        ),
        migrations.DeleteModel(
            name='KnowledgeSource',
        ),
        migrations.DeleteModel(
            name='RetrievalSettings',
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=64)),
                ('canonical_locator', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('title', models.CharField(max_length=200)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', '公开'), ('internal', '内部')], max_length=8)),
                ('document_schema', models.CharField(max_length=64)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding_space', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_source',
                'permissions': [('read_internal', '读取内部资料'), ('maintain_source', '维护来源')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'canonical_locator'), name='source_locator_unique'), models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'internal'])), name='source_visibility_valid')],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='ContextUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='catalog.knowledgesource')),
                ('key', models.CharField(max_length=100)),
                ('ordinal', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('locator', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'context_unit',
                'ordering': ['ordinal'],
                'constraints': [models.UniqueConstraint(fields=('source', 'key'), name='context_key_unique')],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='EvidenceUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.contextunit')),
                ('key', models.CharField(max_length=100)),
                ('ordinal', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('retrieval_text', models.TextField()),
                ('knowledge_type', models.CharField(default='concept', max_length=64)),
                ('locator', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('embedding', models.JSONField()),
            ],
            options={
                'db_table': 'evidence_unit',
                'ordering': ['ordinal'],
                'constraints': [models.UniqueConstraint(fields=('context', 'key'), name='evidence_key_unique')],
                'indexes': [],
            },
        ),
    ]
